eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8086/eureka

server:
  port: 8081
spring:
  application:
    name: api-gateway-service

  cloud:
    gateway:
      routes:
      - id: amazonModule
        uri: http://localhost:8083/
        predicates:
        - Path=/students/**
     